-- RedAnt update 3: UK lead-generation copy rewrite, real URLs, industry + city pages.
-- Safe to run more than once. Run AFTER schema.sql, data.sql and update-2.sql.

-- ---------- structure ----------
ALTER TABLE industries ADD COLUMN IF NOT EXISTS h1 TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS meta_title TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS meta_desc TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS faqs_json TEXT;
ALTER TABLE services   ADD COLUMN IF NOT EXISTS path_card_text TEXT;

CREATE TABLE IF NOT EXISTS locations (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE,
  city TEXT,
  h1 TEXT,
  intro TEXT,
  local_example TEXT,
  meta_title TEXT,
  meta_desc TEXT,
  order_num INTEGER DEFAULT 0
);
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

-- ---------- service pages: new URLs + copy ----------
UPDATE landing_pages SET slug='website-refresh'       WHERE slug='48-hour-website-refresh';
UPDATE landing_pages SET slug='web-design'            WHERE slug='website-design';
UPDATE landing_pages SET slug='wordpress-developer'   WHERE slug='wordpress-development';
UPDATE landing_pages SET slug='website-care-plans'    WHERE slug='care-plans';
UPDATE landing_pages SET slug='social-media-graphics' WHERE slug='brand-and-social-graphics';

UPDATE landing_pages SET headline='*48-hour website refresh* for UK small businesses: £199', subtext='Your website has the right content but looks dated, loads slowly or breaks on phones. We rebuild the design, speed and mobile layout in two days, keeping your words, your brand and your page addresses so your Google rankings are protected.', cta_text='Claim my £199 refresh', meta_title='48-Hour Website Refresh UK | £199 Fixed | RedAnt', meta_desc='Website refresh for UK small businesses. Modern, mobile-first and faster in 48 hours for a fixed £199. Keep your content and brand.', status='published' WHERE slug='website-refresh';
UPDATE landing_pages SET headline='*Affordable website design* for UK small businesses', subtext='A custom website built around how your customers search, compare and choose. Designed to look credible, load fast and make it easy to call or book.', cta_text='Book a free discovery call', meta_title='Affordable Website Design UK | From £499 | RedAnt', meta_desc='Custom 5 or 10-page websites for UK small businesses from £499. Mobile-first, fast, SEO-ready and fully owned by you. Fixed prices.', status='published' WHERE slug='web-design';
UPDATE landing_pages SET headline='*WordPress web designer* for UK businesses', subtext='A WordPress and Elementor site you can edit yourself: change prices, add photos and publish news without calling a developer. Fast, secure and set up properly from day one.', cta_text='Get a WordPress quote', meta_title='WordPress Web Designer UK | Elementor Sites | RedAnt', meta_desc='WordPress and Elementor websites you can edit yourself, built fast and secure for UK small businesses. Get a quote today.', status='published' WHERE slug='wordpress-developer';
UPDATE landing_pages SET headline='*Local SEO* for UK small businesses: get found in your town', subtext='When someone searches "plumber near me" or "physio in Leeds", you want to be in the top three on Google Maps. We optimise your Google Business Profile and your website so local customers find you first.', cta_text='Get my free local SEO check', meta_title='Local SEO UK | Google Maps Ranking | RedAnt', meta_desc='Local SEO for UK small businesses: Google Business Profile, local keywords and location pages so nearby customers find you first.', status='published' WHERE slug='local-seo';
UPDATE landing_pages SET headline='*Website maintenance plans* for UK businesses from £29 a month', subtext='Updates, backups, security and hosting handled for you, so your website never goes down, gets hacked or falls out of date.', cta_text='Start a care plan', meta_title='Website Maintenance Plans UK | £29/mo | RedAnt', meta_desc='Website care plans from £29 a month: UK-based hosting, daily backups, SSL, updates and security monitoring for small businesses.', status='published' WHERE slug='website-care-plans';
UPDATE landing_pages SET headline='*Facebook and Instagram ad graphics* for UK businesses from £99', subtext='Scroll-stopping ad creatives, logo refinements and social templates that match your website and make your ads work harder.', cta_text='Order a graphics pack', meta_title='Facebook & Instagram Ad Graphics UK | RedAnt', meta_desc='Facebook and Instagram ad graphics, logo refinements and social templates for UK businesses from £99.', status='published' WHERE slug='social-media-graphics';

-- ---------- services ----------
UPDATE services SET slug='website-refresh', name='48-Hour Website Refresh', icon='⚡', price_from=199, short_desc='Turn a dated website into a fast, mobile-friendly one in two days for a fixed price.', path_card_text='My website looks dated. Refresh it in 48 hours for £199.', order_num=1 WHERE slug IN ('48-hour-website-refresh','website-refresh');
UPDATE services SET slug='web-design', name='New Website Design', icon='🎨', price_from=499, short_desc='Custom 5 or 10-page websites built to look credible, load fast and make it easy to call or book.', path_card_text='I need a new website. Custom 5 or 10-page sites from £499.', order_num=2 WHERE slug IN ('new-website-design','web-design');
UPDATE services SET slug='wordpress-developer', name='WordPress Websites', icon='⚙️', price_from=NULL, short_desc='Elementor builds you can edit yourself. Fast, secure and set up properly from day one.', path_card_text='I need a WordPress site I can edit. Elementor builds, fast and secure.', order_num=3 WHERE slug IN ('wordpress-custom-dev','wordpress-developer');
UPDATE services SET slug='local-seo', name='Local SEO & Google Maps', icon='🔍', price_from=NULL, short_desc='Google Business Profile and local SEO so customers in your town find you first.', path_card_text='I''m not showing up on Google. Local SEO and Google Business Profile.', order_num=4 WHERE slug IN ('local-seo-setup','local-seo');
UPDATE services SET slug='website-care-plans', name='Website Care Plans', icon='🛡️', price_from=29, short_desc='Updates, backups, security and hosting handled for you from £29 a month.', path_card_text='I want someone to look after it. Care plans from £29 a month.', order_num=5 WHERE slug IN ('website-care-plans','website-care-plans');
INSERT INTO services (slug,name,icon,price_from,short_desc,path_card_text,order_num) VALUES ('social-media-graphics','Ad & Social Graphics','🖼️',99,'Facebook and Instagram ad creatives, logo refinements and social templates.','I need ads and social graphics. Facebook and Instagram creatives from £99.',6) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, price_from=EXCLUDED.price_from, short_desc=EXCLUDED.short_desc, path_card_text=EXCLUDED.path_card_text, order_num=EXCLUDED.order_num;

-- ---------- pricing ----------
DELETE FROM pricing_plans;
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('48-Hour Refresh','£199','Updating a dated site fast','Launch offer','["Modern responsive design", "Mobile-first layout with tap-to-call button", "Speed optimisation", "Basic on-page SEO (titles, headings, meta descriptions)", "Contact form that emails you", "7 days of free revisions"]',1);
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('5-Page Starter','£499','Sole traders, local services','','["Home, About, Services, Contact and Reviews", "Mobile-first design", "Contact form and Google Maps embed", "Basic SEO setup and SSL", "7 days of revisions, full ownership"]',2);
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('10-Page Growth','£899','Businesses wanting to rank locally','Recommended','["Dedicated service pages", "UK local SEO structure and a blog", "Mobile-first design", "Contact form and Google Maps embed", "Basic SEO setup and SSL", "7 days of revisions, full ownership"]',3);
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('Essential Care','£29/mo','Peace of mind','','["UK-based SSD hosting", "Daily off-site backups", "SSL certificate", "Monthly plugin updates", "30 minutes of content edits"]',4);
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('Growth Care','£59/mo','Ongoing edits and priority support','Most popular','["Everything in Essential Care", "1 hour of monthly edits", "Security monitoring", "Priority WhatsApp support"]',5);
INSERT INTO pricing_plans (name,price,billing_type,badge,features_json,order_num) VALUES ('Ad & Social Graphics','from £99','Facebook and Instagram campaigns','','["Facebook and Instagram ad creatives", "Logo refinements", "Social templates that match your website"]',6);

-- ---------- industries ----------
DELETE FROM industries;
INSERT INTO industries (slug,name,h1,intro,problems_json,cta_text,faqs_json,meta_title,meta_desc,order_num) VALUES ('clinics','Clinics & Healthcare','Website design for UK clinics and healthcare practices','Patients choose a clinic they trust within seconds. We build calm, accessible sites with online booking, clear treatments and fees, and local SEO so new patients find you.','["Patients cannot find the booking link on a phone", "Treatments and prices are hard to find", "Pages load slowly, so anxious patients leave"]','Get a free review of your clinic website','[{"q": "Can you add online booking?", "a": "Yes. We can add booking and enquiry forms, or link to the booking system you already use. We do not give clinical or regulatory advice, so please check your own professional body''s rules on advertising."}, {"q": "How much does a website for a clinic cost?", "a": "A 48-hour refresh of an existing site is £199. A new 5-page site is £499 and a 10-page site is £899. All prices are fixed, so you know the cost before we start."}, {"q": "Can I update the website myself afterwards?", "a": "Yes. On WordPress and Elementor builds you can edit text, images and prices yourself, and we give you a short training video. You own your site and code once you''ve paid in full."}]','Web Design for Clinics UK | RedAnt','Website design for UK clinics and healthcare practices: accessible, mobile-friendly sites with clear treatments, fees and booking.',1);
INSERT INTO industries (slug,name,h1,intro,problems_json,cta_text,faqs_json,meta_title,meta_desc,order_num) VALUES ('trades','Trades & Construction','Websites for UK tradespeople and builders','Win more local jobs with a site that loads fast on a phone, shows your best work and puts a Call Now button under every thumb.','["No clear Call Now button on mobile", "Photos of past work are missing or slow to load", "The site does not show the towns you cover"]','Get a free review of your trade website','[{"q": "Will customers be able to call me straight from the site?", "a": "Yes. Every page gets a tap-to-call button and a short enquiry form that emails you."}, {"q": "How much does a website for a tradesperson cost?", "a": "A 48-hour refresh of an existing site is £199. A new 5-page site is £499 and a 10-page site is £899. All prices are fixed, so you know the cost before we start."}, {"q": "Can I update the website myself afterwards?", "a": "Yes. On WordPress and Elementor builds you can edit text, images and prices yourself, and we give you a short training video. You own your site and code once you''ve paid in full."}]','Web Design for Trades UK | RedAnt','Websites for UK tradespeople and builders that load fast on mobile, show your work and make it easy for customers to call.',2);
INSERT INTO industries (slug,name,h1,intro,problems_json,cta_text,faqs_json,meta_title,meta_desc,order_num) VALUES ('coaches','Coaches & Wellbeing','Website design for coaches, therapists and wellbeing brands','A warm, professional site with booking, email sign-up and testimonials that turns curious visitors into clients.','["It is unclear what you offer and who it is for", "No easy way to book a call or join a mailing list", "No testimonials or proof that builds trust"]','Get a free review of your coaching website','[{"q": "Can you add a booking calendar and email sign-up?", "a": "Yes. We can connect a booking tool and a newsletter sign-up such as Mailchimp, so visitors can book or subscribe from any page."}, {"q": "How much does a website for a coach or therapist cost?", "a": "A 48-hour refresh of an existing site is £199. A new 5-page site is £499 and a 10-page site is £899. All prices are fixed, so you know the cost before we start."}, {"q": "Can I update the website myself afterwards?", "a": "Yes. On WordPress and Elementor builds you can edit text, images and prices yourself, and we give you a short training video. You own your site and code once you''ve paid in full."}]','Web Design for Coaches UK | RedAnt','Website design for coaches, therapists and wellbeing brands with booking, email sign-up and testimonials that win clients.',3);
INSERT INTO industries (slug,name,h1,intro,problems_json,cta_text,faqs_json,meta_title,meta_desc,order_num) VALUES ('pubs','Pubs & Hospitality','Websites for UK pubs, cafes and restaurants','Show your menu, events and opening hours clearly and take bookings, with Google Maps visibility that fills tables.','["Menus are PDFs that are hard to read on a phone", "Opening hours and events are out of date", "No easy way to book a table"]','Get a free review of your venue website','[{"q": "Can the menu and opening hours be easy to update?", "a": "Yes. On WordPress builds you can edit your menu, events and opening hours yourself, and we help set up your Google Business Profile so hours match everywhere."}, {"q": "How much does a website for a pub or restaurant cost?", "a": "A 48-hour refresh of an existing site is £199. A new 5-page site is £499 and a 10-page site is £899. All prices are fixed, so you know the cost before we start."}, {"q": "Can I update the website myself afterwards?", "a": "Yes. On WordPress and Elementor builds you can edit text, images and prices yourself, and we give you a short training video. You own your site and code once you''ve paid in full."}]','Web Design for Pubs UK | RedAnt','Websites for UK pubs, cafes and restaurants: clear menus, events, opening hours and bookings, with Google Maps visibility.',4);

-- ---------- city pages ----------
DELETE FROM locations;
INSERT INTO locations (slug,city,h1,intro,local_example,meta_title,meta_desc,order_num) VALUES ('web-design-london','London','Web designer in London: fixed prices from £199','London is one of the most competitive places in the UK to be found online. Customers compare several businesses before they call, so a slow or dated site quietly costs you enquiries. We help London sole traders, clinics, studios and local services get a fast, clear, mobile-friendly website at a fixed price.',NULL,'Web Designer in London | Fixed Prices | RedAnt','Web design for London small businesses. Fast, mobile-friendly websites from £199 with fixed prices and direct WhatsApp support.',1);
INSERT INTO locations (slug,city,h1,intro,local_example,meta_title,meta_desc,order_num) VALUES ('web-design-manchester','Manchester','Web designer in Manchester: fixed prices from £199','From independent shops in the city centre to trades and clinics across Salford, Stockport and Trafford, Greater Manchester businesses compete for the same local searches. We build fast, mobile-first websites that make it easy for nearby customers to call, book or enquire.',NULL,'Web Designer in Manchester | Fixed Prices | RedAnt','Web design for Manchester small businesses. Fast, mobile-friendly websites from £199 with fixed prices and direct WhatsApp support.',2);
INSERT INTO locations (slug,city,h1,intro,local_example,meta_title,meta_desc,order_num) VALUES ('web-design-leeds','Leeds','Web designer in Leeds: fixed prices from £199','Leeds and West Yorkshire businesses, from professional services in the city centre to trades covering Headingley, Chapel Allerton and beyond, win work when customers can find them quickly on a phone. We build clear, fast sites and set up local SEO so you show up in your area.',NULL,'Web Designer in Leeds | Fixed Prices | RedAnt','Web design for Leeds small businesses. Fast, mobile-friendly websites from £199 with fixed prices and direct WhatsApp support.',3);
INSERT INTO locations (slug,city,h1,intro,local_example,meta_title,meta_desc,order_num) VALUES ('web-design-birmingham','Birmingham','Web designer in Birmingham: fixed prices from £199','Birmingham and the wider West Midlands cover everything from studios and makers to trades serving Solihull, Edgbaston and Sutton Coldfield. We help local businesses replace slow, dated sites with fast, mobile-friendly ones that turn searches into enquiries.',NULL,'Web Designer in Birmingham | Fixed Prices | RedAnt','Web design for Birmingham small businesses. Fast, mobile-friendly websites from £199 with fixed prices and direct WhatsApp support.',4);
INSERT INTO locations (slug,city,h1,intro,local_example,meta_title,meta_desc,order_num) VALUES ('web-design-liverpool','Liverpool','Web designer in Liverpool: fixed prices from £199','Liverpool and Merseyside have a strong community of independent venues, wellbeing studios, clinics and trades, including across the Wirral and Sefton. We build fast, easy-to-use websites and local SEO that help nearby customers choose you.',NULL,'Web Designer in Liverpool | Fixed Prices | RedAnt','Web design for Liverpool small businesses. Fast, mobile-friendly websites from £199 with fixed prices and direct WhatsApp support.',5);

-- ---------- FAQs ----------
DELETE FROM faqs;
INSERT INTO faqs (question,answer,category,order_num) VALUES ('How much does a small business website cost in the UK?','Typical UK agencies charge £2,000 to £5,000 or more. At RedAnt, a website refresh is £199, a 5-page site is £499 and a 10-page site is £899, all fixed prices.','General',1);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('Can you really refresh a website in 48 hours?','Yes, when you have an existing site and content. We reuse your text and brand, and update design, mobile layout and speed. Larger rebuilds take 2 to 4 weeks.','General',2);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('Do I own my website?','Yes. Once you''ve paid in full, the site and code are 100% yours.','General',3);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('Will changing my website hurt my Google rankings?','We keep your page addresses and content structure and add SEO improvements, which protects your existing rankings. No one can guarantee rankings, but we take care not to break what already works.','General',4);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('Do you work with UK businesses from outside the UK?','Yes. We work UK hours and communicate by WhatsApp, email and video call. Your site is built to UK standards, including UK GDPR and PECR cookie compliance.','General',5);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('How do payments work?','50% deposit to start and the balance when you''re happy. You can pay by bank transfer or card.','General',6);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('Can I update the website myself?','Yes. On WordPress and Elementor builds you can edit text, images and prices, and we give you a short training video.','General',7);
INSERT INTO faqs (question,answer,category,order_num) VALUES ('What if I don''t like the result?','You get 7 days of free revisions after launch so it is exactly right.','General',8);

-- ---------- guides (drafts: add the article body in the admin, then set status to published) ----------
INSERT INTO blog_posts (slug,title,excerpt,body,category,publish_date,status) VALUES ('website-redesign-checklist-uk','Website redesign checklist for UK small businesses','A practical checklist to run before you redesign your website, with a free PDF to download.','','Guide','2026-10-10','draft') ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_posts (slug,title,excerpt,body,category,publish_date,status) VALUES ('rank-on-google-maps-local-seo-guide','How to rank on Google Maps: a local SEO guide for UK trades','A step-by-step guide to getting your business into the top three on Google Maps.','','Local SEO','2026-10-10','draft') ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_posts (slug,title,excerpt,body,category,publish_date,status) VALUES ('wix-vs-wordpress-uk-small-business','Wix vs WordPress for UK small businesses: which is better?','An honest comparison of Wix and WordPress on cost, control, speed and SEO.','','Comparison','2026-10-10','draft') ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_posts (slug,title,excerpt,body,category,publish_date,status) VALUES ('uk-gdpr-cookie-compliance-website-guide','Is your website UK GDPR and cookie compliant? A simple guide','A plain-English guide to UK GDPR and PECR cookie rules for small business websites.','','Compliance','2026-10-10','draft') ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_posts (slug,title,excerpt,body,category,publish_date,status) VALUES ('website-mistakes-that-cost-uk-clinics-patients','10 website mistakes that cost UK clinics new patients','The most common website problems that stop new patients from booking.','','Healthcare','2026-10-10','draft') ON CONFLICT (slug) DO NOTHING;

-- ---------- trust: remove unverified sample reviews and the reserved (non-working) phone number ----------
DELETE FROM testimonials;
DELETE FROM settings WHERE key = 'phone' AND regexp_replace(value, '[^0-9]', '', 'g') ~ '^(44|0)?2079460';
